version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
    ports:
      - '3001:443'
    restart: always
    env_file:
      - .prod.env
    command: npm run start

volumes:
  pgadmin-data:

networks:
  appNetwork:
    driver: bridge
